import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Providers from './providers'
import Image from 'next/image'
import ThemeButton from './components/themeButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Dicionario',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning lang="pt-br">
      <body className={inter.className}>
        <Providers >
          <header>
            <nav className=' flex justify-between items-center'>
              <ul className='gap-6 flex'>
                <li>
                  <Image
                    src='/book.svg'
                    alt='Imagem de um livro'
                    width={42}
                    height={42}
                  />
                </li>
              </ul>
              <ThemeButton/>
            </nav>
          </header>

          <main>
            {children}
          </main>
        </Providers>
      </body>

    </html>
  )
}
